name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@0f720e83521d609f4d0f69c5f370e60c9f9e93ef
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: xHyroM
          template: markdown
          filename: README.md
          markdown: https://raw.githubusercontent.com/xHyroM/xHyroM/master/.github/metrics.template.md
          config_output: markdown
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Bratislava
          plugin_achievements: yes
          plugin_activity: false
          plugin_activity_limit: 0
          plugin_lines: yes
          plugin_followup: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 1%
          plugin_projects: yes
          plugin_projects_limit: 4
          repositories_skipped: discord-datamining, xeon
